name: Build Linux

on:
  push:
    branches: [ master ]

jobs:
  container:
    runs-on: ubuntu-latest
    container: rockylinux:8
    steps:
    - uses: actions/checkout@v2
    - name: Get deps
      run: |
        dnf install dnf-plugins-core -y
        dnf install epel-release -y
        dnf config-manager --set-enabled powertools
        dnf update
        yum install -y SDL2-devel ninja-build gtk3-devel
        ninja
      shell: bash
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-linux
        prerelease: true
        title: Gpuvis Linux
        files: |
          build/gpuvis
